### ISSUE TITLE
Getting started instructions no longer work

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python-hugo-theme#100]
The problem is that `shortcodes.md` no longer exists but is generated from the script in `tools/`.

Following the instrucions: https://theme.scientific-python.org/getstarted/, you get an error at step 5:

```bash
make serve
ERROR 2022/01/27 20:17:33 [en] REF_NOT_FOUND: Ref "shortcodes": "~/scientific-python-hugo-theme/scientific-python-hugo-theme/doc/content/getstarted.md:63:60": page not found
```

This can be remedied by adding an extra step prior to `make serve`, e.g. `python tools/render_shortcode_docs.py > doc/content/shortcodes.md`.

Perhaps this can be added to the `Makefile` or integrated into the build process in some other fashion.

**Comment by rossbar** [comment]
i.e. no longer work for the specific case of building the example site. I'll close this since it's not generally relevant. One way that this might be improved is to add a README to the `doc/` folder which emphasizes that the example site should be built with `make` and not with the typical `hugo` CLI.

**Comment by stefanv** [comment]
If the instructions aren't executable that seems like something we should fix?

**Comment by rossbar** [comment]
Good point, I guess the `gettingstarted` instructions *do* use the `doc/` folder as the example site. I got confused because this error is only reproducible if you are copying to `my-website` from a *clean* working directory of `scientific-python-hugo-theme`

**Comment by jarrodmillman** [comment]
The `gettingstarted` instructions are for using the theme with your own site (not for building the theme website).  I think they are correct for their intended use (i.e., if you follow the instructions on the page).  Maybe the phrase ("To use the theme") isn't clear.  Would the phrase
```
To use the theme for your own website (e.g., `my-website`), ...
```
be clearer?

We could also add a warning to the page stating these instructions are not for building the website for the theme itself.

**Comment by rossbar** [comment]
The wording suggestion is clearer, but I don't think it's sufficient - the instructions explicitly use `cp -r scientific-python-hugo-theme/doc my-website` as the example site to be built. Without something like this, users won't be able to test the theme out without already having some content in `my-website`. That may be fine, but AFAIK the hugo themes typically include a working example site so that potential adopters can get a feel for the theme without actually having to have content for their own site.
