### ISSUE TITLE
Advertise that this theme is used by large projects

### ISSUE THREAD

**Issue by tupui** [scientific-python/scientific-python-hugo-theme#121]
Would be good to have on the first page a list of projects using the theme.

**Comment by rossbar** [comment]
Similar to how [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/) lists major projects that have adopted it on their landing page.

**Comment by jarrodmillman** [comment]
Here is what we currently have:
![screenshot](https://user-images.githubusercontent.com/123428/154187549-4ffbe489-16e5-48a2-add5-37fe993a98ce.png)
PRs welcome!!

**Comment by tupui** [comment]
Since we still have some leftover from Fresh, we can either use something like Section1 or something like the showcase section from Hugo https://github.com/gohugoio/gohugoioTheme/tree/master/layouts/showcase

**Comment by jeromtom** [comment]
Hey, I have started working on this issue. It would be great if it was assigned to me.

**Comment by stefanv** [comment]
Go for it, @jeromtom!

**Comment by alphapapa** [comment]
@jeromtom I assigned this issue to you, as requested.  :)  I see your PR #121.  Is it ready for review, or are you still working on it?  Thanks.

**Comment by stefanv** [comment]
Closing, ref: https://github.com/scientific-python/scientific-python-hugo-theme/pull/216#issuecomment-1787944080
