### ISSUE TITLE
youtube pages

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#154]
Incorporate [layouts/shortcodes/youtube_page.html](https://github.com/scientific-python/scientific-python.org/pull/223/commits/c92660b1b8465d1aaac2c6cb63f381e25c09f103#diff-01d9b6eb9739851ceaa385ec3af846ba99c4ed48921c31619d2595411cf82b80) in [youtube.html](https://github.com/scientific-python/scientific-python-hugo-theme/blob/main/layouts/shortcodes/youtube.html) and document.

See https://github.com/scientific-python/scientific-python.org/pull/223 and https://github.com/scientific-python/learn.scientific-python.org/pull/10.

Note that scientific-python.org still has at one remaining instance of the `youtube_page` shortcode:
https://github.com/scientific-python/scientific-python.org/blob/main/content/news/specs-announced-scipy2021/index.md

**Comment by stefanv** [comment]
See #155
