### ISSUE TITLE
Video gallery

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#17]
@juanis2112 Could you link to the spyder docs with embedded youtube videos and transcripts.

**Comment by juanis2112** [comment]
Here is the link with the PR that implements it https://github.com/spyder-ide/spyder-docs/pull/124/files
and here it the link to how it looks like https://docs.spyder-ide.org/current/videos/first-steps-with-spyder.html

**Comment by stefanv** [comment]
See https://github.com/scientific-python/scientific-python-hugo-theme/pull/29
