### ISSUE TITLE
Modify social media logos in the Footer

### ISSUE THREAD

**Issue by AsavariA** [scientific-python/scientific-python-hugo-theme#187]
In accordance with [issue #441](https://github.com/numpy/numpy.org/issues/441) of the [numpy.org](https://github.com/numpy/numpy.org) repository.

I am ready with a PR which solves this issue in this way - 

color - colorSecondary
color on hover - white(#fff)
size - 2.3em (which was previously 1.5em, anything greater than that seems too big and out of proportion)

Let me know your thoughts :)

![image](https://user-images.githubusercontent.com/77312781/177027270-318678be-1789-43f7-ab97-7bd2f49f713e.png)

**Comment by tupui** [comment]
Hi @AsavariA thank you for reporting. It seems that the change is wanted on NumPy's side so I am +1 on this. Feel free to open a PR and we will ping relevant people during the review 😃
