### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by tupui** [scientific-python/scientific-python-hugo-theme#192]
I have noticed a few alignment issues on the footer and hero banner. Interestingly it seems fine on SciPy's page for instance. Maybe this just happens if elements are too big.

The footer is not centered if you resize the window to a small screen. Some elements do not wrap and just disappear. Lastly, the vertical alignment is not correct and I think we should reduce the footer size.
<img width="300" alt="Screenshot 2022-08-05 at 19 42 02" src="https://user-images.githubusercontent.com/23188539/183908938-c210be6c-a265-4d32-afc9-42cb8b958bd9.png">

There is no padding on the hero banner when resized
<img width="300" alt="Screenshot 2022-08-05 at 19 42 40" src="https://user-images.githubusercontent.com/23188539/183908958-8e4ae853-c4a6-4ae1-a625-54083fbfeaf6.png">

**Comment by alphapapa** [comment]
@tupui Thanks.  Assigning to myself and will investigate.
