### ISSUE TITLE
Render anchor for headings so they can be easily copied

### ISSUE THREAD

**Issue by stefanv** [scientific-python/scientific-python-hugo-theme#203]
![2022-10-05_10:29:34](https://user-images.githubusercontent.com/45071/194123976-56d8d78b-f90a-44c1-8ba6-1ac42601ee13.png)

**Comment by alphapapa** [comment]
@stefanv Do you mean that you want the link anchor rendered as in that picture, as a chain that the user can right-click to copy the link to?  Or should the heading text itself be linkified so the user can right-click it to get the link (which wouldn't require the appearance to change, but we could add a hover effect, of course)?  Or we could even do both.  :)

Feel free to assign this to me, of course.  Thanks.
