### ISSUE TITLE
Unify w/ pydata sphinx theme

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#225]
- [ ] color schemes
- [ ] variable names
- [ ] config files

**Comment by alphapapa** [comment]
As explained in our meeting the other day, we can more easily make changes in this project than in pydata-sphinx-theme, so we'll generally try to follow its example.

Doing this well will require some familiarity with both projects, so I'll treat this as a longer-term project and dig into it as I learn about them.

**Comment by alphapapa** [comment]
In our meeting now, here's the basic plan we've got:

1.  [ ]  Add Sass to our build process.
2.  [ ]  Add Makefile rule to take Sass from the pydata-sphinx-module repository, copy the files into our project, build them into CSS, and place them in the right place to be served as part of our theme.
3. [ ] Begin editing our HTML/CSS to use the parts from the pydata-sphinx-theme (e.g. editing our CSS classes, using their variable names, etc).

**Comment by alphapapa** [comment]
Ok, as a first step, I've pushed https://github.com/scientific-python/scientific-python-hugo-theme/commit/03d2d9ca346586d00d926c627a3c6c7bf7c63481 which adds a rule to the Makefile to pull the SCSS files from the `pydata-sphinx-theme` repo and add imports for them to a single `all.scss` file.  Next is to have that file built into a CSS file by Hugo and served with the site.  I'll work on that tomorrow.

@jarrodmillman @brianhawthorne

**Comment by alphapapa** [comment]
Closing in favor of new meta-issue: https://github.com/scientific-python/scientific-python-hugo-theme/issues/302
