### ISSUE TITLE
Add hover-link to headers

### ISSUE THREAD

**Issue by stefanv** [scientific-python/scientific-python-hugo-theme#232]

**Comment by alphapapa** [comment]
Hi @stefanv,

I'll be glad to take care of this, but would you give me a bit more detail about what you're wanting?  Thanks.

**Comment by stefanv** [comment]
[Something like this](https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/24), but with link icons appearing after the heading.

It can look like it does in the [hugo docs](https://gohugo.io/templates/introduction/#basic-syntax). Links can appear when you hover over the heading (ideal) or always be there but change color.

**Comment by alphapapa** [comment]
@stefanv Thanks.  Is this what you meant in #203, or is that something else?
