### ISSUE TITLE
Improving the appearance of the `.keyfeatures` boxes

### ISSUE THREAD

**Issue by alphapapa** [scientific-python/scientific-python-hugo-theme#258]
As has been noted, the appearance of the `.keyfeatures` boxes could be improved.  Especially when displayed in the [dark mode theme](https://github.com/scientific-python/scientific-python-hugo-theme/pull/233#issuecomment-1642856766), it leaves something to be desired.

I'd suggest redesigning them to not use shadows, which should significantly improve the appearance on dark-mode, and probably look nicer on light-mode as well.

For inspiration, we could consider the [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/), which has some boxes at the top of that page, although they seem a bit plain.  I'd like to try imitating its "See also" box below, which seems like a nice balance of aesthetics and usability.

**Comment by jarrodmillman** [comment]
The boxes on this site are also fairly nice: https://learn.scientific-python.org/development/
