### ISSUE TITLE
Restore project icon positioning

### ISSUE THREAD

**Issue by stefanv** [scientific-python/scientific-python-hugo-theme#261]
In https://github.com/scientific-python/scientific-python-hugo-theme/pull/230, I didn't notice how much the logo size and positioning changed. It would be good to get them back to the way they were:

<img src="https://user-images.githubusercontent.com/601365/236992421-69a6ffc5-28f7-4b3f-ba3a-39a6d2da9068.png"/>

It's especially noticeable on http://scipy.org

**Comment by jarrodmillman** [comment]
See https://github.com/numpy/numpy.org/pull/668#issuecomment-1721771418

**Comment by jarrodmillman** [comment]
I am not sure I like the alignment we had before. I think it looks a little off that Community developed and the Get Started button appear to be left aligned. But I don't have a strong opinion.
