### ISSUE TITLE
Improvements to `.pagination` class (e.g. seen on `blog.`)

### ISSUE THREAD

**Issue by alphapapa** [scientific-python/scientific-python-hugo-theme#279]
@jarrodmillman pointed out some improvements needed to the appearance of the page links at the bottom of the "All posts" page on blog.scientific-python.org: https://blog.scientific-python.org/posts/

<details><summary>Screenshots</summary>
<p>

![blog scientific-python org_posts_ (1)](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/489d4970-6301-4d1b-9c26-5132c91c891f)
![blog scientific-python org_posts_](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/d752c796-4f42-4cf3-82a2-0fe3afb26787)
![blog scientific-python org_posts_(iPad Mini)](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/ce15df46-0ec3-443d-b159-10de8f6b07f5)

</p>
</details> 

* Their visibility and "clickability" is poor
* On narrower screens, they are drawn on top of each other, making them unreadable and unclickable

**Comment by stefanv** [comment]
Also, we wanted to change the All Posts page to very condensely list the posts. In that case, it's not even clear that we need paging anymore. Post title + date + author is all we need, and then we can probably list 100 posts on one page.

**Comment by alphapapa** [comment]
Having a large number of articles on a single page might not be good for mobile devices.  I'd guess that we'll need to have the per-page limit be configurable and support pagination, even if it's not much needed on blog.scientific-python.org.

I'll make a new issue to track condensing the layout.  Thanks.

**Comment by stefanv** [comment]
Looks like the paginator was removed in f2fe7aa4732bc5042dcaaca9f4e462211e2a2431
