### ISSUE TITLE
BUG: change fonts on website to a font type that includes ő and ű

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python-hugo-theme#285]
This maybe a hugo theme issue rather than a website one, please move the issue upstream if needed.

<img width="369" alt="Screenshot 2023-10-03 at 09 40 54" src="https://github.com/scientific-python/scientific-python.org/assets/6788290/957dafb3-3702-47e3-9603-ad582ffa4265">

**Comment by stefanv** [comment]
I just tested, and this should be fixed by the pending switch to PyData-Sphinx-Theme fonts:

```
-apple-system, BlinkMacSystemFont, Segoe UI, "Helvetica Neue", Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol
```

**Comment by bsipocz** [comment]
I don't see this any more (a lot has changed anyway), so closing this issue for now.
