### ISSUE TITLE
SciPy logo background

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#290]
The SciPy logo has a white background in dark mode:
![2023-10-16T12:17:27,621314937-07:00](https://github.com/scientific-python/scientific-python-hugo-theme/assets/123428/3c427992-2e45-4611-a230-623e228398a7)

The other currently endorsing projects look find, but we should check that the others look ok (e.g., matplotlib, pandas, zarr).

**Comment by tupui** [comment]
Are the logo coming from the md files? like here [core-projects/scipy.md](https://github.com/scientific-python/specs/blob/main/core-projects/scipy.md)? If yes then maybe we can just point to the svg which is directly here https://github.com/scipy/archive/blob/main/branding/logos/scipy_logo.svg

**Comment by tupui** [comment]
Actually #216 should close that right?

**Comment by jarrodmillman** [comment]
> Actually #216 should close that right?

No, that won't impact this.
