### ISSUE TITLE
Grants background on scientific-python.org

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#291]
The grant boxes are a little hard to read (due to the contrast) in dark mode:
![2023-10-16T12:19:49,821890920-07:00](https://github.com/scientific-python/scientific-python-hugo-theme/assets/123428/dec624cc-eb75-4c9d-8f17-0b904cdb32ec)

https://scientific-python.org/grants/

**Comment by alphapapa** [comment]
With the changes in these PRs:

* https://github.com/scientific-python/scientific-python-hugo-theme/pull/292
* https://github.com/scientific-python/scientific-python.org/pull/502

The grants page now looks like this:

<details><summary>Details</summary>
<p>

![Screen Shot 2023-10-17 at 14 45 41-fullpage](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/7eeac160-1250-42ec-a8a7-94cdc8100ab3)
![Screen Shot 2023-10-17 at 14 45 45-fullpage](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/315d1cd2-606f-4a22-8626-c086599e6fe6)


</p>
</details> 

The changes include some minor unification of CSS classes between the theme, the blog, and this site.

Please let me know what you think.  Thanks.

@jarrodmillman @stefanv
