### ISSUE TITLE
Switching to Dart Sass (from LibSass)

### ISSUE THREAD

**Issue by alphapapa** [scientific-python/scientific-python-hugo-theme#305]
As mentioned on the [node-sass](https://www.npmjs.com/package/node-sass) page, LibSass and Node Sass are deprecated, and it's recommended to move onto [Dart Sass](https://sass-lang.com/dart-sass).

A WIP branch is pursuing this: https://github.com/scientific-python/scientific-python-hugo-theme/pull/303

Documentation for Hugo: https://gohugo.io/hugo-pipes/transpile-sass-to-css/#dart-sass

**Comment by stefanv** [comment]
Closed by #303
