### ISSUE TITLE
Key boxes overflow incorrectly

### ISSUE THREAD

**Issue by stefanv** [scientific-python/scientific-python-hugo-theme#341]
![Screenshot_20231030-224218](https://github.com/scientific-python/scientific-python-hugo-theme/assets/45071/19749feb-6304-40ba-99cd-f2998a1ee3d7)

**Comment by jarrodmillman** [comment]
We should also make this look more like it used to, but we should use pst styling and colors.
![2023-10-31T08:23:52,437087264-07:00](https://github.com/scientific-python/scientific-python-hugo-theme/assets/123428/06f682ab-3e23-461b-9633-1a320f3f8f57)

**Comment by jarrodmillman** [comment]
I  removed mobile b/c the same thing happens on the desktop.
