### ISSUE TITLE
GitHub stats

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#40]
(This is an idea from @melissawm)  We should add functionality to query data from github contributions and shows a few plots around those stats. It would be great if this could be a service in a website for people to query
E.g. how many new contributors joined in the last 6 months? How many of those actually made more than 1 contribution? Are the spikes around sprints sustainable? Etc

We have code for this already, but it would be nice to make it more integrated with the theme or to have a central DB for several projects.

**Comment by stefanv** [comment]
https://github.com/chaoss/augur

**Comment by jarrodmillman** [comment]
I had trouble finding where the augur reports live.  I think this is it for the Kubernetes project:
https://k8s.devstats.cncf.io

**Comment by stefanv** [comment]
> I had trouble finding where the augur reports live. I think this is it for the Kubernetes project: https://k8s.devstats.cncf.io

I think this is a grafana dashboard.

**Comment by tupui** [comment]
It's a really cool idea! I like the centralization idea both for the DB and the dashboards. Regardless of the solution which is used, it would be nice if we provided a way to easily download the raw data that we are pulling. This way users can do the analysis they want and even propose some new view on the dashboards.

**Comment by jarrodmillman** [comment]
Maybe devstats.scientific-python.org.

**Comment by jarrodmillman** [comment]
https://chaoss.github.io/grimoirelab-tutorial/

**Comment by jarrodmillman** [comment]
http://augur.osshealth.io/repo/chaoss/grimoirelab-kibiter/overview

**Comment by jarrodmillman** [comment]
See https://devstats.scientific-python.org/.

**Comment by tupui** [comment]
This is awesome!! 👏
