### ISSUE TITLE
Sidebar / shortcuts

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#41]
Two possibly related issues:

- [x] I can't figure out what `sidebar: true/false` does.  It is part of the fresh theme and is used in numpy.org.
- [x] I can't figure out how to populate the "Shortcuts" in what I think is the sidebar.  They showup for numpy.org, but not scientific-python.org or scipy.org. (see #42)

**Comment by stefanv** [comment]
We now know that `sidebar` enables a side-popout menu.  We don't use it in this theme, but it looks like this:

![2021-11-09_19:26:48](https://user-images.githubusercontent.com/45071/141044380-68d5d4f6-938c-42b7-9d1f-337e286ca5d7.png)

**Comment by stefanv** [comment]
This issue possibly ready to close?
