### ISSUE TITLE
Galleries

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#45]
See https://github.com/scipy/scipy.org/issues/414.

It would be nice if we could combine a script (like thishttps://github.com/networkx/networkx/blob/main/tools/team_list.py) that uses the GitHub API to generate the team galleries.  for example,
- https://networkx.org/documentation/stable/developer/about_us.html

We may want to use the gallery stuff from scientific-python.org.

**Comment by stefanv** [comment]
Implemented in #49
