### ISSUE TITLE
Color contrast on page footer

### ISSUE THREAD

**Issue by melissawm** [scientific-python/scientific-python-hugo-theme#457]
Hi folks, when checking the page recently I noticed that the hover/highlight color on links gives a low contrast on the page footer:

![Screenshot_20240125_213738](https://github.com/scientific-python/scientific-python-hugo-theme/assets/3949932/aaca073d-4981-42cf-919f-14d82623715c)

As a quick check, I got the following on https://coolors.co/contrast-checker/8045e5-013243

![Screenshot_20240125_213308](https://github.com/scientific-python/scientific-python-hugo-theme/assets/3949932/91b4905b-adfa-4c39-ab7a-7a02c8dfc924)

I believe the violet is inherited from the PyData Sphinx Theme, so not sure what the right solution would be here.

**Comment by jarrodmillman** [comment]
I've been meaning to fix that. I will resurrect a previous #368 and ping you on it!
