### ISSUE TITLE
Use markdown links (not relref or ref shortcodes)

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#568]
Hugo 0.122 added link render hooks (so we don't need to use the relref or ref shortcodes anymore): https://gohugo.io/render-hooks/links/

See https://github.com/scientific-python/learn.scientific-python.org/pull/146 for example.

**Comment by alphapapa** [comment]
@jarrodmillman I've pushed PRs for these repos, all of the ones I could find that use `relref` or `ref` links in their content:

- https://github.com/scientific-python/blog.scientific-python.org/pull/213
- https://github.com/numpy/numpy.org/pull/743
- https://github.com/scientific-python/scientific-python.org/pull/624
- https://github.com/scientific-python/specs/pull/313

Please let me know if I've missed any, or if any other changes are needed.  Thanks.

**Comment by jarrodmillman** [comment]
Thanks! I merged the ones that were ready to go (or only needed slight tweaking). The blog one looks like it has more tweaks needed, which I will for you to sort out. I will review once the CI passes.
