### ISSUE TITLE
MAINT: why is label called "Bug fix"

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python-hugo-theme#619]
It's weird to label a bug report as "Bug fix", can we drop the "fix" part?

~(I didn't want to do it without asking)~ I can't do it

**Comment by jarrodmillman** [comment]
I don't label issues. I've been using the labels for PRs to autogenerate release notes.

**Comment by stefanv** [comment]
Not sure whether that means you prefer no to have issue big label or what. I'm fine with whatever.

**Comment by jarrodmillman** [comment]
I've never paid attention to labels on issues. I don't care if someone wants to take the time to label issues.
