### ISSUE TITLE
Make the "get started with this theme" more prominent

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python-hugo-theme#65]
I don't have many in the way of concrete ideas here, but just noting on an experience I had recently trying to start a new hugo site from scratch with the theme in the way I'm used to doing it (i.e. following the [hugo quickstart guide](https://gohugo.io/getting-started/quick-start/)).

The problem is that this theme has a lot of preconfiguration "built-in" so to speak - if a user tries to just include the theme as a submodule and start creating the site, it doesn't work and requires tweaking to get to the point where the site will build. Therefore, I think it's important that the [recommended getting-started guide](https://theme.scientific-python.org/getstarted/) is as visible as possible (e.g. linked from the README). It might also be good to add a warning somewhere about not trying to use the theme out-of-the-box.

**Comment by tupui** [comment]
I think this is linked (or should be done at the same time) to #58

**Comment by alphapapa** [comment]
@tupui Can this issue also be closed now?  :)

**Comment by tupui** [comment]
Hi @alphapapa, from my perspective I think so.
