### ISSUE TITLE
Matching style with Sphinx docs

### ISSUE THREAD

**Issue by sreekarchigurupati** [scientific-python/scientific-python-hugo-theme#83]
Hi,
I am trying to use this theme for building a website for my python project. Is there any corresponding sphinx theme that can be used for docs to match style. Similar to the way scipy.org is using

Thanks

**Comment by rossbar** [comment]
Many scientific Python projects includin scipy are using the [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/) for documentation.

**Comment by tupui** [comment]
I confirm, on SciPy we have almost the bare theme from PyData. Have a look at SciPy's main repo in the doc folder.

**Comment by sreekarchigurupati** [comment]
Thank you so much. Will try to use this theme
