### ISSUE TITLE
Adding layout to index page without modifying submodule

### ISSUE THREAD

**Issue by sreekarchigurupati** [scientific-python/scientific-python-hugo-theme#85]
Hi,
I am using this theme repo as a git submodule and would like to avoid making any changes in it.
Is there any way to add layouts in my project and add them to the index page without modifying the theme repo? I have seen some layouts added to the numpy.org website in this manner. When i try to do this, Hugo is unable to find the partial I defined. Kindly advise.

Thanks
Sreekar

**Comment by tupui** [comment]
Hi 👋 it's a bit hard to help without more details about your setup and file hierarchy. You should be able to copy the structure of the theme for your site and adjust the files you want. Then Hugo should look at your files first.
